### ISSUE TITLE
Not compatible with Portable Playnite

### ISSUE THREAD

**Issue by darklinkpower** [Garulf/Playnite-Plugin#1]
Currently it looks only for the default location in appdata but this location is not used for portable installations

**Comment by darklinkpower** [comment]
Forget it, restarting Flow fixed it :/

**Comment by Garulf** [comment]
By default it should look into your `appdata` folder. If your Playnite is in a custom location (portable mode) you can provide your Playnite's location in settings here: 

![image](https://user-images.githubusercontent.com/535299/148774680-d5bdc0e0-5453-459b-9545-9ff31822659f.png)
