### ISSUE TITLE
Playnite Plugin Complexity Needs Toned Down.

### ISSUE THREAD

**Issue by Nickyfan7** [Garulf/Playnite-Plugin#18]
I've tried to link playnite to Flow Launcher but I think it should be noted where it's looking for your library so it cuts down on the confusion or maybe even include a manual in the plugin files that tells you where it's looking for your library. As setup is a bit tricky for the first time user.

For many they will try to lead it to C:\Users\%USERNAME%\AppData\Roaming\Playnite\ExtensionsData\FlowLauncherExporter instead of where it's actually looking in just: C:\Users\tyler\AppData\Roaming\Playnite it also didn't appear to auto-fill in the path for me/default to where it needs to default if the settings are left blank but it doesn't and simply says it can't find a library file, I'll include a log file if it helps (hopefully so)
[plugin.log](https://github.com/Garulf/Playnite-Plugin/files/9224723/plugin.log)

I would reccomend trying to simplify the process of linking it with say a manual included with the plugin or simply have it auto-connect to playnite's database.

**Comment by Garulf** [comment]
Should be much better in https://github.com/Garulf/Playnite-Plugin/pull/23

version 2.0.0

Sadly there is no way for a Python application to access Playnite's database directly. At this time LiteDB is not compatible with Python
