### ISSUE TITLE
Can't seach game past 1 character

### ISSUE THREAD

**Issue by poziel** [Garulf/Playnite-Plugin#19]
I can't seem to search a game past 1 character.
![image](https://user-images.githubusercontent.com/22062561/185227165-2569a06a-7802-4818-92d3-45c80648473c.png)

With only 1 character it seems it shows me some different game, but past 1 character, the plugin just show me my last launched game.

To show more data, even with the full name of the game, it still doesn't show first in the list:
![image](https://user-images.githubusercontent.com/22062561/185228904-0952c40c-fb1e-4261-8f15-865cf00a34b7.png)

An example with 1 character of a game then 2 characters (it should keep this result on top of the list, right?). I am trying to get [Swag and Sorcery](https://store.steampowered.com/app/929010/Swag_and_Sorcery/) here:
![image](https://user-images.githubusercontent.com/22062561/185228960-310b2209-b531-49b5-ba94-4cfae01c9e33.png)
![image](https://user-images.githubusercontent.com/22062561/185229000-98a8cf4f-33bd-4fd0-96e9-15a5af1ddae4.png)

**Comment by Garulf** [comment]
Sorry I somehow did not get a notification for your issue. Looks like the fuzzy matching is being a bit odd. The newer version uses basic string matching but is usually more reliable.

**Comment by Garulf** [comment]
Should be much better in https://github.com/Garulf/Playnite-Plugin/pull/23

version 2.0.0
