### ISSUE TITLE
Request to launch custom actions

### ISSUE THREAD

**Issue by Heeervas** [Garulf/Playnite-Plugin#24]
Hi!

A huge fan of this plugin, but lately I have been facing a situtation which I believe can be awesome to add.

This is the ability to run custom commands when launching, for example now I use a custom action to launch games in borderless mode, with the -popupwindow and in playnite it gets a bit messy.

Would be possible since this access the path, to add parameters in the launcher? Like "pn genshin impact -popupwindow" or something??

Thanks!

**Comment by Garulf** [comment]
Sorry, this plugin just tells Playnite which game to launch. Any arguments would have to be configured in Playnite.
