### ISSUE TITLE
whe I check off Hide Uninstalled, BUT When I search it goes Back ON

### ISSUE THREAD

**Issue by Browl3** [Garulf/Playnite-Plugin#42]
![Screenshot 2024-12-20 153333](https://github.com/user-attachments/assets/a1fffa22-c039-4306-97ff-1dd307523984)
When i search Its supposed to SHOW the Uninstalled, because Hide Uninstalled is Turned OFF, But when I search, the it goes back on so I cant search the uninstalled one .
![Screenshot 2024-12-20 154214](https://github.com/user-attachments/assets/f0985a13-c371-4a26-8f2e-ef83d8cddf2a)
I cant Uncheck it and apply or save , ?

**Comment by Browl3** [comment]
OK I Reinstalled The plugging slightly Differently then Worked

**Comment by DatHypnoboi** [comment]
I'm having the same issue, was there something you did in particular to fix the issue, or did just reinstalling the plugin work?
